
services:
  mealpedant_backup_client:
    image: mealpedant_backup_client:0.3.2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mealpedant_backup_client
    volumes:
      - $HOME/mealpedant_backup.d/backups:/backups
      - $HOME/mealpedant_backup.d/.env:/app_env/.env:ro
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - mealpedant_backup_client-net
    deploy:
      resources:
        limits:
          memory: 128M
networks:
  mealpedant_backup_client-net:
    name: mealpedant_backup_client-net
