
services:
  mealpedant_backup_pi:
    image: mealpedant_backup_pi:0.1.11
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mealpedant_backup_pi
    volumes:
      - $HOME/mealpedant_backup.d/backups:/backups
      - $HOME/mealpedant_backup.d/.env:/app_env/.env:ro
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ipc: private
    restart: always
    networks:
      - mealpedant_backup_pi-net
    logging:
      options:
        max-size: 4mb
    deploy:
      resources:
        limits:
          memory: 16M
networks:
  mealpedant_backup_pi-net:
    name: mealpedant_backup_pi-net
